In [1]:
import pandas as pd
dataset=pd.read_csv("data.csv")
print(dataset)

   country   age   salary purchased
0   france  44.0  72000.0        no
1    spain  27.0  48000.0       yes
2  germany  30.0  54000.0        no
3    spain  38.0  61000.0        no
4  germany  40.0      NaN       yes
5   france  35.0  58000.0       yes
6    spain   NaN  52000.0        no
7   france  48.0  79000.0       yes
8  germany  50.0  83000.0        no
9   france  37.0  67000.0       yes


In [2]:
import numpy as np
x=dataset.iloc[:,: -1].values
y=dataset.iloc[:,-1].values
print(x)
print(y)

[['france' 44.0 72000.0]
 ['spain' 27.0 48000.0]
 ['germany' 30.0 54000.0]
 ['spain' 38.0 61000.0]
 ['germany' 40.0 nan]
 ['france' 35.0 58000.0]
 ['spain' nan 52000.0]
 ['france' 48.0 79000.0]
 ['germany' 50.0 83000.0]
 ['france' 37.0 67000.0]]
['no' 'yes' 'no' 'no' 'yes' 'yes' 'no' 'yes' 'no' 'yes']


In [3]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)
print(x_train)
print(x_test)
print(y_train)
print(y_test)

[['spain' nan 52000.0]
 ['germany' 40.0 nan]
 ['france' 44.0 72000.0]
 ['spain' 38.0 61000.0]
 ['spain' 27.0 48000.0]
 ['france' 48.0 79000.0]
 ['germany' 50.0 83000.0]
 ['france' 35.0 58000.0]]
[['germany' 30.0 54000.0]
 ['france' 37.0 67000.0]]
['no' 'yes' 'no' 'no' 'yes' 'yes' 'no' 'yes']
['no' 'yes']


In [4]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(x[:,1:3])
x[:,1:3]=imputer.transform(x[:,1:3])
print(x)

[['france' 44.0 72000.0]
 ['spain' 27.0 48000.0]
 ['germany' 30.0 54000.0]
 ['spain' 38.0 61000.0]
 ['germany' 40.0 63777.77777777778]
 ['france' 35.0 58000.0]
 ['spain' 38.77777777777778 52000.0]
 ['france' 48.0 79000.0]
 ['germany' 50.0 83000.0]
 ['france' 37.0 67000.0]]


In [5]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
x=np.array(ct.fit_transform(x))
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [6]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)
print(y)
print(x)

[0 1 0 0 1 1 0 1 0 1]
[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [7]:
import pandas as pd
import numpy as np
dataset=pd.read_csv('Salary_Data.csv')
print(dataset)

    YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0


In [8]:
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values
print(x)
print(y)

[[ 1.1]
 [ 1.3]
 [ 1.5]
 [ 2. ]
 [ 2.2]
 [ 2.9]
 [ 3. ]
 [ 3.2]
 [ 3.2]
 [ 3.7]
 [ 3.9]
 [ 4. ]
 [ 4. ]
 [ 4.1]
 [ 4.5]
 [ 4.9]
 [ 5.1]
 [ 5.3]
 [ 5.9]
 [ 6. ]
 [ 6.8]
 [ 7.1]
 [ 7.9]
 [ 8.2]
 [ 8.7]
 [ 9. ]
 [ 9.5]
 [ 9.6]
 [10.3]
 [10.5]]
[ 39343.  46205.  37731.  43525.  39891.  56642.  60150.  54445.  64445.
  57189.  63218.  55794.  56957.  57081.  61111.  67938.  66029.  83088.
  81363.  93940.  91738.  98273. 101302. 113812. 109431. 105582. 116969.
 112635. 122391. 121872.]


In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)
print(x_train)
print(x_test)
print(y_train)
print(y_test)

[[ 9.5]
 [ 2. ]
 [ 8.7]
 [ 7.9]
 [ 8.2]
 [ 2.2]
 [ 1.5]
 [ 9. ]
 [ 3. ]
 [ 5.9]
 [ 4.1]
 [ 3.2]
 [ 9.6]
 [ 1.3]
 [ 5.1]
 [ 1.1]
 [ 4.9]
 [10.5]
 [10.3]
 [ 3.7]
 [ 3.2]
 [ 4. ]
 [ 4. ]
 [ 2.9]]
[[5.3]
 [7.1]
 [3.9]
 [6. ]
 [4.5]
 [6.8]]
[116969.  43525. 109431. 101302. 113812.  39891.  37731. 105582.  60150.
  81363.  57081.  54445. 112635.  46205.  66029.  39343.  67938. 121872.
 122391.  57189.  64445.  56957.  55794.  56642.]
[83088. 98273. 63218. 93940. 61111. 91738.]


In [16]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)
print(y)
print(x)

[ 1  4  0  3  2  7 11  5 14 10 13  6  8  9 12 16 15 18 17 20 19 21 22 26
 24 23 27 25 29 28]
[[ 1.1]
 [ 1.3]
 [ 1.5]
 [ 2. ]
 [ 2.2]
 [ 2.9]
 [ 3. ]
 [ 3.2]
 [ 3.2]
 [ 3.7]
 [ 3.9]
 [ 4. ]
 [ 4. ]
 [ 4.1]
 [ 4.5]
 [ 4.9]
 [ 5.1]
 [ 5.3]
 [ 5.9]
 [ 6. ]
 [ 6.8]
 [ 7.1]
 [ 7.9]
 [ 8.2]
 [ 8.7]
 [ 9. ]
 [ 9.5]
 [ 9.6]
 [10.3]
 [10.5]]


In [17]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x_train,x_test)

ValueError: Found input variables with inconsistent numbers of samples: [24, 6]

In [15]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train[:,3:]=sc.fit_transform(x_train[:,3:])
x_test[:,3:]=sc.transform(x_test[:,3:])
print(x_train)
print(x_test)

ValueError: Found array with 0 feature(s) (shape=(24, 0)) while a minimum of 1 is required by StandardScaler.